JPAAA, no view controllers
danny73210/homework_mateacademy pull request #12
Opened 2019-01-15 17:06 UTC by danny73210

2019-01-18 18:54 UTC, Orbit419 commented on src/main/java/jpa/entity/Patient.java
> +    @ManyToMany(cascade = {CascadeType.ALL})
по коду нормально, но по логике у тебя один тест относится к многим пациентам, не знаю нужно ли править это

2019-01-18 18:58 UTC, Orbit419 commented on src/main/java/jpa/service/Service.java
> +    void deleteById(int id);
deleteById принимает int, нужно Id или хотя бы Integer

2019-01-18 19:05 UTC, rkrylov requested changes

2019-01-18 19:05 UTC, Orbit419 commented on src/main/java/jpa/entity/Patient.java
> +    protected Set<Test> tests = new HashSet<>();
по коду нормально, но по логике у тебя один тест относится к многим пациентам, не знаю нужно ли править это

2019-01-18 19:05 UTC, Orbit419 commented on src/main/java/jpa/service/Service.java
> +    void deleteById(int id);
deleteById принимает int, нужно Id или хотя бы Integer

2019-01-20 07:03 UTC, boroda4436 requested changes

2019-01-20 07:03 UTC, boroda4436 commented on src/main/java/jpa/service/Service.java
> +    void deleteById(int id);
@danny73210 please, fix it

2019-01-20 07:03 UTC, boroda4436 commented on src/main/java/jpa/entity/Patient.java
> +    protected Set<Test> tests = new HashSet<>();
@danny73210 it will be better to use relation "One patient - Many tests"

2019-01-20 07:03 UTC, boroda4436 commented on src/main/java/jpa/entity/TestSkin.java
> +        return "TestSkin{" +
Tostring without base class fields?

2019-01-20 07:03 UTC, boroda4436 commented on src/main/java/jpa/service/TestService.java
> +public class TestService {
Just empty class? Where is extends Service ... ?

2019-01-20 07:03 UTC, boroda4436 commented on src/main/java/jpa/entity/Patient.java
> +import javax.persistence.*;
do not use * import

2019-01-20 07:03 UTC, boroda4436 commented on src/main/java/jpa/Main.java
> +        PatientDao patientDao = new PatientDaoImpl(em, Patient.class);
@danny73210 Create Config class. Use this to create dao, service instances

2019-01-20 07:03 UTC, boroda4436 commented on src/main/java/jpa/Main.java
> +import jpa.entity.*;
@danny73210 don't use * import

2019-02-05 17:40 UTC, merged